const TodoItemTypes = {
    ADD_ITEM: 'ADD_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',

    TOOGLE_COMPLETED: 'TOGGLE_COMPLETED',
    TOGGLE_COMPLETED_ALL: 'TOGGLE_COMPLETED_ALL',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}

export default TodoItemTypes;