const TodoItemTypes = {
    ADD_ITEM: 'ADD_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',

    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',

    TOOGLE_COMPLETED: 'TOGGLE_COMPLETED',
    TOGGLE_SELECT_ALL: 'TOGGLE_SELECT_ALL',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}

export default TodoItemTypes;